baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alpha Church"
theme = ['alpha-church']
themesDir = "themes"

# cd hugo/vkaras/themes/alpha-church/exampleSite ; hugo server -D

enableEmoji = true
customCSS = ["", ""]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level theme.
#Use the weight= to specify the order of menu items, and the parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Domů"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "O mně"
    url = "/about"
    weight = 2

  # [[menu.main]]
  #   name = "About Us"
  #   parent = "About"
  #   url = "/about"
  #   weight = 1

  # [[menu.main]]
  #   name = "Leaders"
  #   parent = "About"
  #   url = "/leaders"
  #   weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 3

  # [[menu.main]]
  #   name = "Sermons"
  #   url = "/sermons"
  #   parent = "Resources"
  #   weight = 1

  # [[menu.main]]
  #   name = "Blog"
  #   url = "/posts"
  #   parent = "Resources"
  #   weight = 2

  [[menu.main]]
    name = "Objednejte se"
    url = "/#call-to-action"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Masáže a poradenství Věra Karásková | Brno"
  subtitle = ""
  author = "Věra Karásková"

  bible_popups = true

  [params.podcast]
    title = "Listen to Alpha Church"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    num_episodes = "10"

  [params.map]
    # For Open Street Map widgets
    latitude = "49.205868"
    longitude = "16.580870"
    zoom = "13"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "img/physio.jpg"

      [[params.landing.banner.button]]
        url = "/#call-to-action"
        text = "Objednejte se"
        type = "special"

        [[params.landing.banner.button]]
        url = "#feature-images"
        text = "Druhy masáží"

    #Details for the box below the banner
    [params.landing.services]
      title = "Masáž je nejlepší investice do Vašeho zdraví"
      text = "Mé masážni studio najdete v blízkosti centra Brna na adrese Eleonory Voračické 5. Parkování je možné před vjezdem domu."
      map_location = "Brno žabovřesky"

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = false

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-bone"
        icon_pack = "fas"
        accent = "3"
        title = "Léčebná masáž Tuina"
        text = "Čínská léčebná masáž s využitím akupunkturních bodů harmonizuje tělo i ducha, podporuje správný tok životní energie a správnou funkci orgánů v lidském těle."

      [[params.landing.feature_icons.tile]]
        icon = "fa-child"
        icon_pack = "fas"
        accent = "2"
        title = "Sportovni a relaxacni masaz"
        text = "Klasicka masaz na problemy se zády a krkem. Trvani masaze podle vasi potreby a výsledků léčení."

      [[params.landing.feature_icons.tile]]
        icon = "fa-burn"
        icon_pack = "fas"
        accent = "5"
        title = "Baňkování a moxovani"
        text = "Tato masaz je tradicni a nemeli by ste se ji bat. Pouzivaji se sklenene banky, ktere se nahřejou a přiloží na tělo. Baňka tak podtlakem stimuluje podkoží a ulevuje od bolesti."

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "1"
        title = "Dornova metoda PLUS"
        text = ""

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "1"
        title = "Nahrivani TDP lampou"
        text = ""

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "1"
        title = "Dalsi druhy masazi"
        text = "Reflexni, medova, cokoladova, anticelulitidni, masaz lavovymi kameny"

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = true

      [[params.landing.feature_images.tile]]
        image = ""
        title = "Čínská léčebná masáž TUINA"
        text = "Čínská léčebná masáž s využitím akupunkturních bodů harmonizuje tělo i ducha, podporuje správný tok životní energie a správnou funkci orgánů v lidském těle. Obvyklá doba trvání masáže 1 hodina."
        url = "/tuina"
        button_text="Více"

      [[params.landing.feature_images.tile]]
        image = ""
        title = "Dornova metoda PLUS"
        text = "Srovnává páteř a klouby a ulevuje jim od bolestí. Řeší např. rozdílnou délku nohou, skoliózu, bolesti kolen, ramen, tenisový loket apod. Obvyklá doba trvání masáže 1,5 až 2 hodiny."
        url = "/dornovametoda"
        button_text="Více"

      [[params.landing.feature_images.tile]]
        image = ""
        title = "Sportovní masáž"
        text = "Důmyslné sestavená masáž pro uvolnění těla před nebo po sportovním výkonu. Působí na fyzické tělo i psychiku a podporuje regeneraci. Obvyklá doba trvání masáže 1 hodina."
        url = "/sportovnimasaz"
        button_text="Více"

      [[params.landing.feature_images.tile]]
        image = ""
        title = "Baňkování a moxování"
        text = "Skleněnými nebo plastovými baňkami je vytvářen podtlak, který uvolňuje a prokrvuje tkáně. Moxování - nahříváním akupunkturních bodů pomocí speciálních doutníků, naplněných pelyňkem, uvolňuje ošetřovaný meridián."
        url = "/bankovani"
        button_text="Více"

      [[params.landing.feature_images.tile]]
        image = ""
        title = "Nahřívání TDP lampou"
        text = "Lampu, která vyzařuje 33 minerálů, používám během masáže pro postupné prohřívání páteře, kloubů a dalších bolestivých míst. Teplo krásně uvolní zatuhlá místa a pomáhá od bolesti. Tato lampa se bežně používá v čínských nemocnicích."
        url = "/tdp"
        button_text="Více"

      [[params.landing.feature_images.tile]]
        image = ""
        title = "Reflexní terapie"
        text = "Anticelulitidní, medová, čokoládová a masáž lávovými kameny nabízím na přání pro lepší detoxikaci a regeneraci organismu. Obvyklá doba trvání masáže 1 až 1,5 hodiny."
        url = "/tdp"
        button_text="Více"

      [[params.landing.feature_images.tile]]
        image = ""
        title = "Medová masáž"
        text = "Anticelulitidní, medová, čokoládová a masáž lávovými kameny nabízím na přání pro lepší detoxikaci a regeneraci organismu. Obvyklá doba trvání masáže 1 až 1,5 hodiny."
        url = "/medmas"
        button_text="Více"
      
      [[params.landing.feature_images.tile]]
        image = ""
        title = "Čokoládová masáž"
        text = "Anticelulitidní, medová, čokoládová a masáž lávovými kameny nabízím na přání pro lepší detoxikaci a regeneraci organismu. Obvyklá doba trvání masáže 1 až 1,5 hodiny."
        url = "/cokomas"
        button_text="Více"

      [[params.landing.feature_images.tile]]
        image = ""
        title = "Anticelulitidní masáž se zábalem "
        text = "Anticelulitidní, medová, čokoládová a masáž lávovými kameny nabízím na přání pro lepší detoxikaci a regeneraci organismu. Obvyklá doba trvání masáže 1 až 1,5 hodiny."
        url = "/anticel"
        button_text="Více"

      [[params.landing.feature_images.tile]]
         image = ""
         title = "Masáž lávovými kameny "
         text = ""
         url = "/lavovekameny"
         button_text = "Více"

    [params.landing.CTA]
      heading = "Objednejte se"
      message = "Objednejte se prosím na tomto telefonním čísle 731 683 502. IČO 06824269"

    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    
